//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace basumaruAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basutei
    {
        public int BasuteiId { get; set; }
        public string kigyou { get; set; }
        public string rosenmei { get; set; }
        public string basuteimei { get; set; }
        public double ido { get; set; }
        public double keido { get; set; }
        public string yaneFlg { get; set; }
        public string benchiFlg { get; set; }
        public string noriba { get; set; }
    }
}
