//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace basumaruAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jikokuhyou
    {
        public int JikokuhyouId { get; set; }
        public string kigyou { get; set; }
        public string rosenmei { get; set; }
        public string ikisaki { get; set; }
        public string hidukebunrui { get; set; }
        public string basuteimei { get; set; }
        public string zikoku { get; set; }
        public string hachakuKubun { get; set; }
    }
}
